name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        cd back
        npm install
        cd ../front
        npm install

    - name: Build Backend
      run: |
        cd back
        npm run build
      env:
        CI: ""

    - name: Build Frontend
      run: |
        cd front
        npm run build
      env:
        CI: ""

    - name: Build Docker Image
      run: |
        docker build -t earlystopping:latest .
        docker tag earlystopping:latest earlystopping:$(date +%s)


